/**
 * \file list-mon-race-flags.h
 * \brief monster race flags
 *
 */
/* symbol		type			descr */
RF(NONE,		RFT_NONE,		"")
RF(UNIQUE,		RFT_OBV,		"")
RF(QUESTOR,		RFT_OBV,		"")
RF(MALE,		RFT_OBV,		"")
RF(FEMALE,		RFT_OBV,		"")
RF(GROUP_AI,	RFT_OBV,		"")
RF(NAME_COMMA,	RFT_OBV,		"")
RF(CHAR_CLEAR,	RFT_DISP,		"")
RF(ATTR_RAND,	RFT_DISP,		"")
RF(ATTR_CLEAR,	RFT_DISP,		"")
RF(ATTR_MULTI,	RFT_DISP,		"")
RF(ATTR_FLICKER,RFT_DISP,		"")
RF(FORCE_DEPTH,	RFT_GEN,		"")
RF(FORCE_SLEEP,	RFT_GEN,		"")
RF(FORCE_EXTRA,	RFT_GEN,		"")
RF(SEASONAL,	RFT_GEN,		"")
RF(UNAWARE,		RFT_NOTE,		"")
RF(MULTIPLY,	RFT_NOTE,		"")
RF(REGENERATE,	RFT_NOTE,		"")
RF(FRIGHTENED,	RFT_BEHAV,		"")
RF(NEVER_BLOW,	RFT_BEHAV,		"")
RF(NEVER_MOVE,	RFT_BEHAV,		"")
RF(RAND_25,		RFT_BEHAV,		"")
RF(RAND_50,		RFT_BEHAV,		"")
RF(MIMIC_INV,	RFT_BEHAV,		"")
RF(STUPID,		RFT_BEHAV,		"")
RF(SMART,		RFT_BEHAV,		"")
RF(SPIRIT,		RFT_BEHAV,		"")
RF(POWERFUL,	RFT_BEHAV,		"")
RF(ONLY_GOLD,	RFT_DROP,		"")
RF(ONLY_ITEM,	RFT_DROP,		"")
RF(DROP_40,		RFT_DROP,		"")
RF(DROP_60,		RFT_DROP,		"")
RF(DROP_1,		RFT_DROP,		"")
RF(DROP_2,		RFT_DROP,		"")
RF(DROP_3,		RFT_DROP,		"")
RF(DROP_4,		RFT_DROP,		"")
RF(DROP_GOOD,	RFT_DROP,		"")
RF(DROP_GREAT,	RFT_DROP,		"")
RF(DROP_20,		RFT_DROP,		"")
RF(INVISIBLE,	RFT_DET,		"invisible")
RF(COLD_BLOOD,	RFT_DET,		"sangre fría")
RF(EMPTY_MIND,	RFT_DET,		"no se detecta por telepatía")
RF(WEIRD_MIND,	RFT_DET,		"raramente se detecta por telepatía")
RF(OPEN_DOOR,	RFT_ALTER,		"abrir puertas")
RF(BASH_DOOR,	RFT_ALTER,		"derribar puertas")
RF(PASS_WALL,	RFT_ALTER,		"atravesar paredes")
RF(KILL_WALL,	RFT_ALTER,		"perforar paredes")
RF(SMASH_WALL,	RFT_ALTER,		"destrozar paredes")
RF(MOVE_BODY,	RFT_ALTER,		"empujar monstruos más débiles")
RF(KILL_BODY,	RFT_ALTER,		"destruir monstruos más débiles")
RF(TAKE_ITEM,	RFT_ALTER,		"recoger objetos")
RF(KILL_ITEM,	RFT_ALTER,		"destruir objetos")
RF(CLEAR_WEB,	RFT_ALTER,		"limpiar telarañas")
RF(PASS_WEB,	RFT_ALTER,		"atravesar telarañas")
RF(ORC,			RFT_RACE_N,		"orco")
RF(TROLL,		RFT_RACE_N,		"troll")
RF(GIANT,		RFT_RACE_N,		"gigante")
RF(DRAGON,		RFT_RACE_N,		"dragón")
RF(DEMON,		RFT_RACE_N,		"demonio")
RF(ANIMAL,		RFT_RACE_A,		"natural")
RF(EVIL,		RFT_RACE_A,		"maligna")
RF(UNDEAD,		RFT_RACE_A,		"no muerto")
RF(NONLIVING,	RFT_RACE_A,		"sin vida")
RF(METAL,		RFT_RACE_A,		"metal")
RF(HURT_LIGHT,	RFT_VULN,		"luz brillante")
RF(HURT_ROCK,	RFT_VULN,		"removedor de roca")
RF(HURT_FIRE,	RFT_VULN_I,		"fuego")
RF(HURT_COLD,	RFT_VULN_I,		"frío")
RF(IM_ACID,		RFT_RES,		"ácido")
RF(IM_ELEC,		RFT_RES,		"relámpago")
RF(IM_FIRE,		RFT_RES,		"fuego")
RF(IM_COLD,		RFT_RES,		"frío")
RF(IM_POIS,		RFT_RES,		"veneno")
RF(IM_NETHER,	RFT_RES,		"más allá")
RF(IM_WATER,	RFT_RES,		"agua")
RF(IM_PLASMA,	RFT_RES,		"plasma")
RF(IM_NEXUS,	RFT_RES,		"nexo")
RF(IM_DISEN,	RFT_RES,		"desencantamiento")
RF(NO_FEAR,		RFT_PROT,		"asustado")
RF(NO_STUN,		RFT_PROT,		"aturdido")
RF(NO_CONF,		RFT_PROT,		"confundido")
RF(NO_SLEEP,	RFT_PROT,		"dormido")
RF(NO_HOLD,		RFT_PROT,		"inmovilizado")
RF(NO_SLOW,		RFT_PROT,		"ralentizado")
/* end flags */
