/**
 * \file list-effects.h
 * \brief Lista de efectos
 *
 * name: código del efecto
 * aim: ¿el efecto requiere apuntar?
 * info: etiqueta de información para hechizos
 * args: cuántos argumentos toma la descripción
 * info flags: indicadores para la descripción del objeto
 * description: texto de la descripción
 * menu_name: cadena de formato para el nombre del menú; usar una cadena vacía
 * si no está previsto usarlo desde un menú
 */
/* nombre 							aim		info		args	info flags		description	menu_name */
EFFECT(RANDOM,						false,	NULL,		0,		EFINFO_NONE,	"aleatoriamente ",	"")
EFFECT(DAMAGE,						false,	"hurt",		1,		EFINFO_DICE,	"hace %s de daño al jugador",	"")
EFFECT(HEAL_HP,						false,	"heal",		2,		EFINFO_HEAL,	"cura %s puntos de vida%s",	"curarse")
EFFECT(MON_HEAL_HP,					false,	NULL,		0,		EFINFO_NONE,	"cura puntos de vida al monstruo",	"")
EFFECT(MON_HEAL_KIN,				false,	NULL,		0,		EFINFO_NONE,	"cura puntos de vida a monstruos aliados",	"")
EFFECT(NOURISH,						false,	NULL,		3,		EFINFO_FOOD,	"%s durante %s turnos (%s por ciento)",	"%s %s")
EFFECT(CRUNCH,						false,	NULL,		0,		EFINFO_NONE,	"cruje",	"")
EFFECT(CURE,						false,	NULL,		1,		EFINFO_CURE,	"cura %s",	"curar %s")
EFFECT(TIMED_SET,					false,	NULL,		2,		EFINFO_TIMED,	"inflige %s durante %s turnos",	"infligir %s")
EFFECT(TIMED_INC,					false,	"dur",		2,		EFINFO_TIMED,	"extiende %s durante %s turnos",	"extender %s")
EFFECT(TIMED_INC_NO_RES,			false,	"dur",		2,		EFINFO_TIMED,	"extiende %s durante %s turnos (irresistible)",	"extender %s")
EFFECT(MON_TIMED_INC,				false,	NULL,		2,		EFINFO_TIMED,	"aumenta el %s del monstruo en %s turnos",	"")
EFFECT(TIMED_DEC,					false,	NULL,		2,		EFINFO_TIMED,	"reduce la duración de %s en %s turnos",	"reducir %s")
EFFECT(GLYPH,						false,	NULL,		1,		EFINFO_NONE,	"inscribe un glifo bajo ti",	"inscribir un glifo")
EFFECT(WEB,							false,	NULL,		0,		EFINFO_NONE,	"crea una telaraña",	"crear una telaraña")
EFFECT(RESTORE_STAT,				false,	NULL,		1,		EFINFO_STAT,	"restaura tu %s",	"restaurar %s")
EFFECT(DRAIN_STAT,					false,	NULL,		1,		EFINFO_STAT,	"reduce tu %s",	"")
EFFECT(LOSE_RANDOM_STAT,			false,	NULL,		1,		EFINFO_STAT,	"reduce una estadística distinta de %s",	"")
EFFECT(GAIN_STAT,					false,	NULL,		1,		EFINFO_STAT,	"aumenta tu %s",	"")
EFFECT(RESTORE_EXP,					false,	NULL,		0,		EFINFO_NONE,	"restaura tu experiencia",	"restaurar experiencia")
EFFECT(GAIN_EXP,					false,	NULL,		1,		EFINFO_CONST,	"otorga %d puntos de experiencia",	"")
EFFECT(DRAIN_LIGHT,					false,	NULL,		0,		EFINFO_NONE,	"drena tu fuente de luz",	"")
EFFECT(DRAIN_MANA,					false,	NULL,		0,		EFINFO_NONE,	"drena algo de maná",	"")
EFFECT(RESTORE_MANA,				false,	NULL,		0,		EFINFO_NONE,	"restaura algo de maná",	"restaurar maná")
EFFECT(REMOVE_CURSE,				false,	NULL,		1,		EFINFO_DICE,	"intenta eliminar una maldición de un objeto con poder %s",	"eliminar maldición")
EFFECT(RECALL,						false,	NULL,		0,		EFINFO_NONE,	"te devuelve de la mazmorra o te lleva a ella tras una breve demora",	"retorno")
EFFECT(DEEP_DESCENT,				false,	NULL,		0,		EFINFO_NONE,	"te teletransporta hasta cinco niveles de mazmorra más abajo del punto más profundo que has alcanzado hasta ahora", "descender a las profundidades")
EFFECT(ALTER_REALITY,				false,	NULL,		0,		EFINFO_NONE,	"crea un nuevo nivel de mazmorra",	"alterar realidad")
EFFECT(MAP_AREA,					false,	NULL,		0,		EFINFO_NONE,	"cartografía el área a tu alrededor",	"cartografiar alrededores")
EFFECT(READ_MINDS,					false,	NULL,		0,		EFINFO_NONE,	"cartografía el área cerca de monstruos detectados recientemente",	"leer mentes")
EFFECT(DETECT_TRAPS,				false,	NULL,		0,		EFINFO_NONE,	"detecta trampas cercanas",	"detectar trampas")
EFFECT(DETECT_DOORS,				false,	NULL,		0,		EFINFO_NONE,	"detecta puertas cercanas",	"detectar puertas")
EFFECT(DETECT_STAIRS,				false,	NULL,		0,		EFINFO_NONE,	"detecta escaleras cercanas",	"detectar escaleras")
EFFECT(DETECT_ORE,					false,	NULL,		0,		EFINFO_NONE,	"detecta vetas cercanas",	"detectar vetas")
EFFECT(SENSE_GOLD,					false,	NULL,		0,		EFINFO_NONE,	"percibe oro cercano",	"percibir oro")
EFFECT(DETECT_GOLD,					false,	NULL,		0,		EFINFO_NONE,	"detecta oro cercano",	"detectar oro")
EFFECT(SENSE_OBJECTS,				false,	NULL,		0,		EFINFO_NONE,	"percibe objetos cercanos",	"percibir objetos")
EFFECT(DETECT_OBJECTS,				false,	NULL,		0,		EFINFO_NONE,	"detecta objetos cercanos",	"detectar objetos")
EFFECT(DETECT_LIVING_MONSTERS,		false,	NULL,		0,		EFINFO_NONE,	"detecta criaturas vivas cercanas",	"detectar vivos")
EFFECT(DETECT_VISIBLE_MONSTERS,		false,	NULL,		0,		EFINFO_NONE,	"detecta criaturas visibles cercanas",	"detectar visibles")
EFFECT(DETECT_INVISIBLE_MONSTERS,	false,	NULL,		0,		EFINFO_NONE,	"detecta criaturas invisibles cercanas",	"detectar invisibles")
EFFECT(DETECT_FEARFUL_MONSTERS,		false,	NULL,		0,		EFINFO_NONE,	"detecta criaturas cercanas susceptibles al miedo",	"detectar miedosos")
EFFECT(IDENTIFY,					false,	NULL,		0,		EFINFO_NONE,	"identifica una runa desconocida en un objeto seleccionado",	"identificar")
EFFECT(DETECT_EVIL,					false,	NULL,		0,		EFINFO_NONE,	"detecta criaturas malignas cercanas",	"detectar maldad")
EFFECT(DETECT_SOUL,					false,	NULL,		0,		EFINFO_NONE,	"detecta criaturas con espíritu cercanas",	"detectar almas")
EFFECT(CREATE_STAIRS,				false,	NULL,		0,		EFINFO_NONE,	"crea una escalera bajo tus pies",	"crear escaleras")
EFFECT(DISENCHANT,					false,	NULL,		0,		EFINFO_NONE,	"desencanta uno de tus objetos equipados",	"desencantar objeto")
EFFECT(ENCHANT,						false,	NULL,		0,		EFINFO_NONE,	"intenta mejorar mágicamente un objeto",	"encantar objeto")
EFFECT(RECHARGE,					false,	"power",	0,		EFINFO_NONE,	"intenta recargar una varita o bastón, destruyéndolo si falla",	"recargar")
EFFECT(PROJECT_LOS,					false,	"power",	1,		EFINFO_SEEN,	"%s que estén en la línea de visión",	"%s en línea de visión")
EFFECT(PROJECT_LOS_AWARE,			false,	"power",	1,		EFINFO_SEEN,	"%s que estén en la línea de visión",	"%s en línea de visión")
EFFECT(ACQUIRE,						false,	NULL,		0,		EFINFO_NONE,	"crea objetos buenos cerca",	"crear objetos buenos")
EFFECT(WAKE,						false,	NULL,		0,		EFINFO_NONE,	"despierta a todos los monstruos dormidos cercanos",	"despertar a todos")
EFFECT(SUMMON,						false,	NULL,		1,		EFINFO_SUMM,	"invoca %s en el nivel actual de la mazmorra",	"invocar %s")
EFFECT(BANISH,						false,	NULL,		0,		EFINFO_NONE,	"elimina del nivel a todas las criaturas de un tipo dado",	"desterrar")
EFFECT(MASS_BANISH,					false,	NULL,		0,		EFINFO_NONE,	"elimina a todas las criaturas cercanas",	"desterrar a todos")
EFFECT(PROBE,						false,	NULL,		0,		EFINFO_NONE,	"te da información sobre la salud y habilidades de los monstruos que puedes ver",	"sondear")
EFFECT(TELEPORT,					false,	"range",	2,		EFINFO_TELE,	"teletransporta %s aleatoriamente %s",	"teletransportar %s %s")
EFFECT(TELEPORT_TO,					false,	NULL,		0,		EFINFO_NONE,	"teletransporta hacia un objetivo",	"teletransportar al objetivo")
EFFECT(TELEPORT_LEVEL,				false,	NULL,		0,		EFINFO_NONE,	"te teletransporta un nivel arriba o abajo",	"teletransportar nivel")
EFFECT(RUBBLE,						false,	NULL,		0,		EFINFO_NONE,	"hace caer escombros a tu alrededor",	"")
EFFECT(GRANITE,						false,	NULL,		0,		EFINFO_NONE,	"hace caer un muro de granito detrás de ti",		"")
EFFECT(DESTRUCTION,					false,	NULL,		1,		EFINFO_QUAKE,	"destruye un área a tu alrededor en forma de círculo de radio %d, y te ciega durante 1d10+10 turnos",	"destruir área")
EFFECT(EARTHQUAKE,					false,	NULL,		1,		EFINFO_QUAKE,	"provoca un terremoto a tu alrededor de radio %d",	"provocar terremoto")
EFFECT(LIGHT_LEVEL,					false,	NULL,		0,		EFINFO_NONE,	"ilumina completamente y cartografía mágicamente el nivel",	"iluminar nivel")
EFFECT(DARKEN_LEVEL,				false,	NULL,		0,		EFINFO_NONE,	"oscurece completamente y cartografía mágicamente el nivel",	"oscurecer nivel")
EFFECT(LIGHT_AREA,					false,	NULL,		0,		EFINFO_NONE,	"ilumina el área circundante",	"iluminar área")
EFFECT(DARKEN_AREA,					false,	NULL,		0,		EFINFO_NONE,	"oscurece el área circundante",	"oscurecer área")
EFFECT(SPOT,						false,	"dam",		4,		EFINFO_SPOT,	"crea una esfera de %s con radio %d, centrada en el jugador y golpeándole, con intensidad total hasta radio %d, causando %s de daño en el centro",	"envolverse con %s")
EFFECT(SPHERE,						false,	"dam",		4,		EFINFO_SPOT,	"crea una esfera de %s con radio %d, centrada en el jugador, con intensidad total hasta radio %d, causando %s de daño en el centro",	"proyectar %s")
EFFECT(BALL,						true,	"dam",		3,		EFINFO_BALL,	"dispara una esfera de %s con radio %d, causando %s de daño en el centro",	"disparar una esfera de %s")
EFFECT(BREATH,						true,	NULL,		3,		EFINFO_BREATH,	"exhala un cono de %s con una anchura de %d grados, causando %s de daño en el origen",	"exhalar un cono de %s")
EFFECT(ARC,							true,	"dam",		3,		EFINFO_BREATH,	"produce un cono de %s con una anchura de %d grados, causando %s de daño en el origen",	"producir un cono de %s")
EFFECT(SHORT_BEAM,					true,	"dam",		3,		EFINFO_SHORT,	"produce un rayo de %s con longitud %d, causando %s de daño",	"producir un rayo de %s")
EFFECT(LASH,						true,	NULL,		2,		EFINFO_LASH,	"dispara un rayo de %s de longitud %d, causando daño determinado por los golpes",	"azotar con %s")
EFFECT(SWARM,						true,	"dam",		3,		EFINFO_BALL,	"dispara una serie de esferas de %s de radio %d, causando %s de daño en el centro de cada una",	"disparar un enjambre de esferas de %s")
EFFECT(STRIKE,						true,	"dam",		3,		EFINFO_BALL,	"crea una esfera de %s con radio %d, causando %s de daño en el centro",	"golpear con %s")
EFFECT(STAR,						false,	"dam",		2,		EFINFO_BOLTD,	"dispara una línea de %s en todas direcciones, causando cada una %s de daño",	"disparar una línea de %s en todas direcciones")
EFFECT(STAR_BALL,					false,	"dam",		3,		EFINFO_BALL,	"dispara esferas de %s con radio %d en todas direcciones, causando %s de daño en el centro de cada una",	"disparar esferas de %s en todas direcciones")
EFFECT(BOLT,						true,	"dam",		2,		EFINFO_BOLTD,	"lanza un proyectil de %s causando %s de daño",	"lanzar un proyectil de %s")
EFFECT(BEAM,						true,	"dam",		2,		EFINFO_BOLTD,	"lanza un rayo de %s causando %s de daño",	"lanzar un rayo de %s")
EFFECT(BOLT_OR_BEAM,				true,	"dam",		2,		EFINFO_BOLTD,	"lanza un proyectil o rayo de %s causando %s de daño",	"lanzar un proyectil o rayo de %s")
EFFECT(LINE,						true,	"dam",		2,		EFINFO_BOLTD,	"crea una línea de %s causando %s de daño",	"crear una línea de %s")
EFFECT(ALTER,						true,	NULL,		1,		EFINFO_BOLT,	"crea una línea que %s",	"crear una línea que %s")
EFFECT(BOLT_STATUS,					true,	NULL,		1,		EFINFO_BOLT,	"lanza un proyectil que %s",	"lanzar un proyectil que %s")
EFFECT(BOLT_STATUS_DAM,				true,	"dam",		2,		EFINFO_BOLTD,	"lanza un proyectil que %s, causando %s de daño",	"lanzar un proyectil que %s")
EFFECT(BOLT_AWARE,					true,	NULL,		1,		EFINFO_BOLT,	"crea un proyectil que %s",	"crear un proyectil que %s")
EFFECT(TOUCH,						false,	NULL,		1,		EFINFO_TOUCH,	"%s en todas las casillas adyacentes",	"%s todos los adyacentes")
EFFECT(TOUCH_AWARE,					false,	NULL,		1,		EFINFO_TOUCH,	"%s en todas las casillas adyacentes",	"%s todos los adyacentes")
EFFECT(CURSE_ARMOR,					false,	NULL,		0,		EFINFO_NONE,	"maldice tu armadura equipada",	"maldecir armadura")
EFFECT(CURSE_WEAPON,				false,	NULL,		0,		EFINFO_NONE,	"maldice tu arma cuerpo a cuerpo equipada",	"maldecir arma")
EFFECT(BRAND_WEAPON,				false,	NULL,		0,		EFINFO_NONE,	"marca tu arma cuerpo a cuerpo equipada",	"marcar arma")
EFFECT(BRAND_AMMO,					false,	NULL,		0,		EFINFO_NONE,	"marca una pila de munición",	"marcar munición")
EFFECT(BRAND_BOLTS,					false,	NULL,		0,		EFINFO_NONE,	"marca virotes con fuego, de forma desequilibrada",	"marcar virotes")
EFFECT(CREATE_ARROWS,				false,	NULL,		0,		EFINFO_NONE,	"usa un bastón para crear una pila de flechas",	"usar bastón para flechas")
EFFECT(TAP_DEVICE,					false,	NULL,		0,		EFINFO_NONE,	"drena energía mágica de un bastón o varita",	"drenar dispositivo")
EFFECT(TAP_UNLIFE,					false,	"dam",		1,		EFINFO_DICE,	"drena %s de maná del monstruo no muerto más cercano, dañándolo",	"drenar no vida")
EFFECT(SHAPECHANGE,					false,	NULL,		0,		EFINFO_NONE,	"cambia la forma del jugador",	"cambiar forma")
EFFECT(CURSE,						true,	"dam",		0,		EFINFO_NONE,	"daña directamente a un monstruo",	"maldecir")
EFFECT(COMMAND,						true,	NULL,		0,		EFINFO_NONE,	"toma el control de un monstruo",	"comandar")
EFFECT(JUMP_AND_BITE,				false,	NULL,		0,		EFINFO_NONE,	"salta al monstruo vivo más cercano y lo muerde",	"saltar y morder")
EFFECT(MOVE_ATTACK,					true,	"blows",	1,		EFINFO_DICE,	"mueve al jugador hasta 4 espacios y ejecuta hasta %d golpes cuerpo a cuerpo",	"moverse y atacar")
EFFECT(SINGLE_COMBAT,				true,	NULL,		0,		EFINFO_NONE,	"se enfrenta a un monstruo en combate singular",	"combate singular")
EFFECT(MELEE_BLOWS,					true,	"blows",	1,		EFINFO_DICE,	"asesta %d golpes contra un monstruo adyacente",	"aporrear")
EFFECT(SWEEP,						false,	"blows",	1,		EFINFO_DICE,	"asesta %d golpes contra todos los monstruos adyacentes",	"barrido")
EFFECT(BIZARRE,						true,	NULL,		0,		EFINFO_NONE,	"hace cosas extrañas",	"hacer cosas extrañas")
EFFECT(WONDER,						true,	NULL,		0,		EFINFO_NONE,	"crea efectos aleatorios e impredecibles",	"crear efectos aleatorios")
EFFECT(SELECT,						false,	NULL,		0,		EFINFO_NONE,	"selecciona uno de ",	"")
EFFECT(SET_VALUE,					false,	NULL,		0,		EFINFO_NONE,	"",					"")
EFFECT(CLEAR_VALUE,					false,	NULL,		0,		EFINFO_NONE,	"",					"")
EFFECT(SCRAMBLE_STATS,					false,  NULL,		0,		EFINFO_NONE,	"", 					"")
EFFECT(UNSCRAMBLE_STATS,				false,	NULL,		0,		EFINFO_NONE,	"",					"")