/**
 * \file list-parser-errors.h
 * \brief Parse errors and descriptions
 */

PARSE_ERROR(NONE,					"(ninguno)")
PARSE_ERROR(BAD_EXPRESSION_STRING,	"cadena de expresión incorrecta")
PARSE_ERROR(ELEMENT_NAME_MISMATCH,	"el nombre del elemento no coincide")
PARSE_ERROR(FIELD_TOO_LONG,			"campo demasiado largo")
PARSE_ERROR(GENERIC,				"error genérico")
PARSE_ERROR(INTERNAL,				"error interno")
PARSE_ERROR(INVALID_ALLOCATION,		"asignación no válida")
PARSE_ERROR(INVALID_COLOR,			"color no válido")
PARSE_ERROR(INVALID_DICE,			"dados no válidos")
PARSE_ERROR(INVALID_EFFECT,			"efecto no válido")
PARSE_ERROR(INVALID_EXPRESSION,		"expresión no válida")
PARSE_ERROR(INVALID_FLAG,			"indicador no válido")
PARSE_ERROR(INVALID_ID_TYPE,		"tipo de id de propiedad de objeto no válido")
PARSE_ERROR(INVALID_ITEM_NUMBER,	"número de objeto no válido")
PARSE_ERROR(INVALID_ITERATE,		"iteración de cálculo de poder no válida")
PARSE_ERROR(INVALID_LIGHTING,		"iluminación no válida")
PARSE_ERROR(INVALID_MESSAGE,		"mensaje no válido")
PARSE_ERROR(INVALID_MONSTER_BASE,	"base de monstruo no válida")
PARSE_ERROR(INVALID_MONSTER,		"raza de monstruo no válida")
PARSE_ERROR(INVALID_MONSTER_ROLE,	"rol de grupo de monstruo no válido")
PARSE_ERROR(INVALID_OBJ_PROP_CODE,	"código de propiedad de objeto no válido")
PARSE_ERROR(INVALID_OPTION,			"opción no válida")
PARSE_ERROR(INVALID_OPERATION,		"operación de cálculo de poder no válida")
PARSE_ERROR(INVALID_PLAY_PROP_CODE,	"código de propiedad de jugador no válido")
PARSE_ERROR(INVALID_PROPERTY,		"tipo de propiedad de objeto no válido")
PARSE_ERROR(INVALID_SLAY,			"matanza no válida")
PARSE_ERROR(INVALID_SPELL_FREQ,		"frecuencia de hechizo no válida")
PARSE_ERROR(INVALID_SPELL_NAME,		"nombre de hechizo no válido")
PARSE_ERROR(INVALID_SPELL_STAT,		"estadística de hechizo no válida")
PARSE_ERROR(INVALID_SUBTYPE,		"subtipo de propiedad de objeto no válido")
PARSE_ERROR(INVALID_VALUE,		"valor no válido")
PARSE_ERROR(MISSING_BLOW_EFF_TYPE,	"falta el tipo de efecto de golpe")
PARSE_ERROR(MISSING_FIELD,			"falta un campo")
PARSE_ERROR(MISSING_OBJ_PROP_TYPE,	"falta el tipo de propiedad de objeto")
PARSE_ERROR(MISSING_PLAY_PROP_TYPE,	"falta el tipo de propiedad de jugador")
PARSE_ERROR(MISSING_RECORD_HEADER,	"falta la cabecera del registro")
PARSE_ERROR(NO_ARTIFACT_NAME,		"nombre de artefacto no encontrado")
PARSE_ERROR(NO_BUILDER_FOUND,		"no se encontró generador")
PARSE_ERROR(NO_FILE_FOUND,			"no se encontró el archivo")
PARSE_ERROR(NO_KIND_FOR_EGO_TYPE,	"no se encontró tipo de objeto para el tipo ego")
PARSE_ERROR(NO_KIND_FOUND,			"no se encontró el tipo de objeto")
PARSE_ERROR(NO_ROOM_FOUND,			"no se encontró sala")
PARSE_ERROR(NON_SEQUENTIAL_RECORDS,	"registros no secuenciales")
PARSE_ERROR(NOT_NUMBER,				"no es un número")
PARSE_ERROR(NOT_RANDOM,				"no es aleatorio")
PARSE_ERROR(NOT_SPECIAL_ARTIFACT,	"no es un artefacto especial")
PARSE_ERROR(OBSOLETE_FILE,			"archivo obsoleto")
PARSE_ERROR(OUT_OF_BOUNDS,			"fuera de los límites")
PARSE_ERROR(OUT_OF_MEMORY,			"memoria agotada")
PARSE_ERROR(REPEATED_DIRECTIVE,		"directiva usada más de una vez")
PARSE_ERROR(TOO_FEW_ENTRIES,		"muy pocas entradas")
PARSE_ERROR(TOO_MANY_ENTRIES,		"demasiadas entradas")
PARSE_ERROR(UNBOUND_EXPRESSION,		"expresión no vinculada")
PARSE_ERROR(UNDEFINED_DIRECTIVE,	"directiva no definida")
PARSE_ERROR(UNRECOGNISED_BLOW,		"golpe no reconocido")
PARSE_ERROR(UNRECOGNISED_BRAND,		"marca no reconocida")
PARSE_ERROR(UNRECOGNISED_SLAY,		"matanza no reconocida")
PARSE_ERROR(UNRECOGNISED_CURSE,		"maldición no reconocida")
PARSE_ERROR(UNRECOGNISED_TRAP,		"trampa no reconocida")
PARSE_ERROR(UNRECOGNISED_TVAL,		"tval no reconocido")
PARSE_ERROR(UNRECOGNISED_SVAL,		"sval no reconocido")
PARSE_ERROR(UNRECOGNISED_PARAMETER,	"parámetro no reconocido")
PARSE_ERROR(VAULT_TOO_BIG,			"bóveda demasiado grande")
PARSE_ERROR(VAULT_DESC_WRONG_LENGTH,"longitud de línea de descripción de bóveda incorrecta")
