/**
 * \file list-mon-message.h
 * \brief Lista de tipos de mensajes de monstruos
 *
 * id           - el nombre constante del mensaje
 * msg          - tipo MSG_ para el mensaje impreso
 * omit_subject - true para omitir el nombre del monstruo antes (ver mon-msg.c)
 * text         - el texto del mensaje
 */

/* id						MSG_GENERIC,	texto */
MON_MSG(NONE,				MSG_GENERIC,	false,	"[es|son] herido[s].")
MON_MSG(DIE,				MSG_KILL,		false,	"muere[n].")
MON_MSG(DESTROYED,			MSG_KILL,		false,	"[es|son] destruido[s].")
MON_MSG(RESIST_A_LOT,		MSG_GENERIC,	false,	"resist[e|en] mucho.")
MON_MSG(HIT_HARD,			MSG_GENERIC,	false,	"[es|son] golpeado[s] con fuerza.")
MON_MSG(RESIST,				MSG_GENERIC,	false,	"resist[e|en].")
MON_MSG(IMMUNE,				MSG_GENERIC,	false,	"[es|son] inmune[s].")
MON_MSG(RESIST_SOMEWHAT,	MSG_GENERIC,	false,	"resist[e|en] un poco.")
MON_MSG(UNAFFECTED,			MSG_GENERIC,	false,	"¡[está|están] intacto[s]!")
MON_MSG(SPAWN,				MSG_GENERIC,	false,	"¡[engendra|engendran]!")
MON_MSG(HEALTHIER,			MSG_GENERIC,	false,	"parece[n] más saludable[s].")
MON_MSG(FALL_ASLEEP,		MSG_GENERIC,	false,	"¡[se] duerme[n]!")
MON_MSG(WAKES_UP,			MSG_GENERIC,	false,	"[se] despierta[n].")
MON_MSG(CRINGE_LIGHT,		MSG_GENERIC,	false,	"¡[se] encoge[n] ante la luz!")
MON_MSG(SHRIVEL_LIGHT,		MSG_KILL,		false,	"¡[se] marchita[n] en la luz!")
MON_MSG(LOSE_SKIN,			MSG_GENERIC,	false,	"¡[pierde|pierden] algo de piel!")
MON_MSG(DISSOLVE,			MSG_KILL,		false,	"¡[se] disuelve[n]!")
MON_MSG(CATCH_FIRE,			MSG_GENERIC,	false,	"¡[se] incendia[n]!")
MON_MSG(BADLY_FROZEN,		MSG_GENERIC,	false,	"[está|están] gravemente congelado[s].")
MON_MSG(SHUDDER,			MSG_GENERIC,	false,	"[se] estremece[n].")
MON_MSG(CHANGE,				MSG_GENERIC,	false,	"¡[cambia|cambian]!")
MON_MSG(DISAPPEAR,			MSG_GENERIC,	false,	"¡[desaparece|desaparecen]!")
MON_MSG(MORE_DAZED,			MSG_GENERIC,	false,	"[está|están] aún más aturdido[s].")
MON_MSG(DAZED,				MSG_GENERIC,	false,	"[está|están] aturdido[s].")
MON_MSG(NOT_DAZED,			MSG_GENERIC,	false,	"ya no [está|están] aturdido[s].")
MON_MSG(MORE_CONFUSED,		MSG_GENERIC,	false,	"parece[n] más confundido[s].")
MON_MSG(CONFUSED,			MSG_GENERIC,	false,	"parece[n] confundido[s].")
MON_MSG(NOT_CONFUSED,		MSG_GENERIC,	false,	"ya no [está|están] confundido[s].")
MON_MSG(MORE_SLOWED,		MSG_GENERIC,	false,	"parece[n] más lento[s].")
MON_MSG(SLOWED,				MSG_GENERIC,	false,	"parece[n] lento[s].")
MON_MSG(NOT_SLOWED	,		MSG_GENERIC,	false,	"[acelera|aceleran].")
MON_MSG(MORE_HASTED,		MSG_GENERIC,	false,	"¡parece[n] incluso más rápido[s]!")
MON_MSG(HASTED,				MSG_GENERIC,	false,	"[empieza|empiezan] a moverse más rápido.")
MON_MSG(NOT_HASTED,			MSG_GENERIC,	false,	"[reduce|reducen] la velocidad.")
MON_MSG(MORE_AFRAID,		MSG_GENERIC,	false,	"¡parece[n] más aterrorizado[s]!")
MON_MSG(FLEE_IN_TERROR,		MSG_FLEE,		false,	"¡[huye|huyen] aterrorizado[s]!")
MON_MSG(NOT_AFRAID,			MSG_GENERIC,	false,	"ya no [tiene|tienen] miedo.")
MON_MSG(HELD,				MSG_GENERIC,    false,  "¡[está|están] paralizado[s] en el lugar!")
MON_MSG(NOT_HELD,			MSG_GENERIC,    false,  "puede[n] moverse de nuevo.")
MON_MSG(DISEN,				MSG_GENERIC,    false,  "¡parece[n] menos mágico[s]!")
MON_MSG(NOT_DISEN,			MSG_GENERIC,    false,  "parece[n] mágico[s] de nuevo.")
MON_MSG(COMMAND,			MSG_GENERIC,    false,  "¡cae bajo tu hechizo!")
MON_MSG(NOT_COMMAND,		MSG_GENERIC,    false,  "ya no está bajo tu control.")
MON_MSG(SHAPE_FAIL,			MSG_GENERIC,    false,  "brilla por un momento.")
MON_MSG(MORIA_DEATH,		MSG_KILL,		true,	"Oyes [un|varios] grito[s] de agonía!")
MON_MSG(DISINTEGRATES,		MSG_KILL,		false,	"¡[se] desintegra[n]!")
MON_MSG(FREEZE_SHATTER,		MSG_KILL,		false,	"¡[se] congela[n] y [se] hace[n] añicos!")
MON_MSG(MANA_DRAIN,			MSG_GENERIC,	false,	"¡[pierde|pierden] algo de maná!")
MON_MSG(BRIEF_PUZZLE,		MSG_GENERIC,	false,	"parece[n] brevemente perplejo[s].")
MON_MSG(MAINTAIN_SHAPE,		MSG_GENERIC,	false,	"mantiene[n] la misma forma.")
MON_MSG(UNHARMED,			MSG_GENERIC,	false,	"[está|están] ileso[s].")
MON_MSG(APPEAR,			MSG_GENERIC,	false,	"¡[aparece|aparecen]!")
MON_MSG(HIT_AND_RUN,		MSG_GENERIC,	true,	"¡Hay una bocanada de humo!")
MON_MSG(QUAKE_DEATH,		MSG_KILL,	false,	"¡[es|son] incrustado[s] en la roca!")
MON_MSG(QUAKE_HURT,		MSG_GENERIC,	false,	"¡[gime|gimen] de dolor!")
/* Mensajes ficticios para el dolor del monstruo - usamos la información del archivo de edición. */
MON_MSG(95,					MSG_GENERIC,	false,	"")
MON_MSG(75,					MSG_GENERIC,	false,	"")
MON_MSG(50,					MSG_GENERIC,	false,	"")
MON_MSG(35,					MSG_GENERIC,	false,	"")
MON_MSG(20,					MSG_GENERIC,	false,	"")
MON_MSG(10,					MSG_GENERIC,	false,	"")
MON_MSG(0,					MSG_GENERIC,	false,	"")
MON_MSG(MAX,				MSG_GENERIC,	false,	"")